### ISSUE TITLE
The helm command is not clear in the documentation

### ISSUE THREAD

**Issue by otaviojava** [ZupIT/charlescd-docs#8]
I've tried:
In the charlescd repository after cloning the project:
```
helm install charlescd charlescd/ -n test
Error: Chart.yaml file is missing
```
I've tried the helm-install folder in the Charles repository:

```
helm install charlescd charlescd/install/helm-chart/ -n test
Error: found in Chart.yaml, but missing in charts/ directory: postgresql, redis, keycloak, rabbitmq
```

**Comment by barbararochazup** [comment]
Hi @otaviojava

To install with helm charts, run the command inside the _**/charlescd/install/helm-chart**_ 

`helm install --create-namespace -n <namespace> charlescd . -f values.yaml`

**Obs.** _`--create-namespace`_  will create namespace only if not already before created

We updated the helm install section to be clearer https://docs.charlescd.io/get-started/installing-charles/installing-via-helm
